(()=>{
const SEARCH_API='https://imdb.iamidiotareyoutoo.com/search';
const JUSTWATCH_API='https://imdb.iamidiotareyoutoo.com/justwatch';
const norm=s=>String(s??'').toLocaleLowerCase('ca').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const providerForUrl=u=>{try{const h=new URL(u).hostname.toLowerCase();if(h==='netflix.com'||h.endsWith('.netflix.com'))return'Netflix';if(h==='disneyplus.com'||h.endsWith('.disneyplus.com'))return'Disney+';if(h==='primevideo.com'||h.endsWith('.primevideo.com')||h==='amazon.com'||h.endsWith('.amazon.com'))return'Prime Video';if(h==='movistarplus.es'||h.endsWith('.movistarplus.es')||h==='movistar.es'||h.endsWith('.movistar.es'))return'Movistar Plus+'}catch{}return null};
const roots=raw=>Array.isArray(raw)?raw:(raw?.items||raw?.results||raw?.data||raw?.titles||raw?.movies||raw?.shows||[raw]);
const walkStrings=(o,out=[],key='')=>{if(o==null)return out;if(Array.isArray(o)){o.forEach(x=>walkStrings(x,out,key));return out}if(typeof o!=='object')return out;for(const [k,v] of Object.entries(o)){if(typeof v==='string')out.push([k,v]);else if(v&&typeof v==='object')walkStrings(v,out,k)}return out};
const first=(o,keys)=>{for(const k of keys)if(o?.[k]!=null&&typeof o[k]!=='object')return String(o[k]);return''};
const idFrom=o=>{const direct=first(o,['imdb_id','imdbId','imdbID','id']);if(/^tt\d+$/i.test(direct))return direct;for(const [,v] of walkStrings(o))if(/^tt\d+$/i.test(v))return v;return''};
const posterFrom=o=>{for(const [k,v] of walkStrings(o)){if(/^https?:\/\//i.test(v)&&/(poster|image|thumbnail|cover|photo)/i.test(k))return v}const id=idFrom(o);return id?`https://imdb.iamidiotareyoutoo.com/photo/${id}`:''};
const streamingLinks=o=>{const f={};for(const [,v] of walkStrings(o)){const p=providerForUrl(v);if(p&&!f[p])f[p]=v}return f};
const normalizeSearch=(raw,q)=>{const out=[],seen=new Set(),needle=norm(q);const visit=x=>{if(!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(visit);return}const title=first(x,['title','name','original_title','originalTitle']);if(title&&norm(title).includes(needle)){const year=first(x,['year','release_year','releaseYear','original_release_year']);const key=norm(title)+'|'+year;if(!seen.has(key)){seen.add(key);out.push({title,year:year?Number(year):null,poster_url:posterFrom(x),streaming_urls:{},movie_url:null,genre:first(x,['genre','genres']),description:first(x,['description','overview','plot','synopsis']),duration_minutes:Number(first(x,['runtime','duration','runtime_minutes']))||null,rating:Number(first(x,['rating','score','vote_average']))||null,providers:[]})}}Object.values(x).forEach(v=>v&&typeof v==='object'&&visit(v))};roots(raw).forEach(visit);return out};
const normalizeJW=(raw,q)=>{const out=[],seen=new Set(),needle=norm(q);const visit=x=>{if(!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(visit);return}const title=first(x,['title','name','original_title','originalTitle']);if(title&&norm(title).includes(needle)){const year=first(x,['year','release_year','releaseYear','original_release_year']),urls=streamingLinks(x),key=norm(title)+'|'+year;if(!seen.has(key)){seen.add(key);out.push({title,year:year?Number(year):null,poster_url:posterFrom(x),streaming_urls:urls,movie_url:Object.values(urls)[0]||null,genre:first(x,['genre','genres']),description:first(x,['description','overview','plot','synopsis']),duration_minutes:Number(first(x,['runtime','duration','runtime_minutes']))||null,rating:Number(first(x,['rating','score','vote_average']))||null,providers:Object.keys(urls)})}}Object.values(x).forEach(v=>v&&typeof v==='object'&&visit(v))};roots(raw).forEach(visit);return out};
const merge=(search,jw)=>{const map=new Map();for(const m of [...search,...jw]){const key=norm(m.title)+'|'+(m.year||'');const old=map.get(key);if(!old){map.set(key,{...m});continue}if(!old.poster_url&&m.poster_url)old.poster_url=m.poster_url;old.streaming_urls={...(old.streaming_urls||{}),...(m.streaming_urls||{})};old.movie_url=old.movie_url||m.movie_url;old.providers=[...new Set([...(old.providers||[]),...(m.providers||[])])];old.genre=old.genre||m.genre;old.description=old.description||m.description;old.duration_minutes=old.duration_minutes||m.duration_minutes;old.rating=old.rating??m.rating}return [...map.values()]};
let items=[],provider='all';
const form=document.querySelector('#discoverForm'),box=document.querySelector('#discoverResults'),status=document.querySelector('#discoverStatus');
function render(){const a=provider==='all'?items:items.filter(m=>m.providers.includes(provider));status.textContent=`${a.length} resultat${a.length===1?'':'s'}`;box.innerHTML=a.slice(0,50).map((m,i)=>`<article class="discover-card"><div class="discover-poster">${m.poster_url?`<img src="${esc(m.poster_url)}" alt="Pòster de ${esc(m.title)}" loading="lazy">`:'<span>🎬</span>'}</div><div class="discover-info"><h3>${esc(m.title)}</h3><p>${m.year||'Any desconegut'}${m.genre?` · ${esc(m.genre)}`:''}</p><div class="discover-providers">${m.providers.map(p=>`<span class="discover-provider">${esc(p)}</span>`).join('')}</div><div class="discover-actions">${m.movie_url?`<a class="secondary" href="${esc(m.movie_url)}" target="_blank" rel="noopener noreferrer">🔗 Veure</a>`:''}<button class="primary" data-v2-add="${i}">+ Afegir a PeliTrack</button></div></div></article>`).join('');box._v2Items=a;fixImages(box)}
function fixImages(root=document){root.querySelectorAll('img').forEach(img=>{if(img.dataset.v2)return;img.dataset.v2='1';const original=img.src;img.onerror=()=>{const phase=img.dataset.v2Fallback||'0';if(phase==='0'){img.dataset.v2Fallback='1';img.src=`/api/poster-from-page?url=${encodeURIComponent(original)}`;return}const id=(original.match(/\/(tt\d+)(?:\?|$)/i)||[])[1];if(phase==='1'&&id){img.dataset.v2Fallback='2';img.src=`https://imdb.iamidiotareyoutoo.com/photo/${id}`;return}img.onerror=null;img.removeAttribute('src');img.parentElement.innerHTML='<span>🎬</span>'}})}
async function search(q){q=q.trim();if(!q)return;status.textContent='Buscant…';box.innerHTML='';try{const [a,b]=await Promise.allSettled([fetch(`${SEARCH_API}?q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}}),fetch(`${JUSTWATCH_API}?q=${encodeURIComponent(q)}&L=es_ES`,{headers:{Accept:'application/json'}})]);const s=a.status==='fulfilled'&&a.value.ok?normalizeSearch(await a.value.json(),q):[];const j=b.status==='fulfilled'&&b.value.ok?normalizeJW(await b.value.json(),q):[];items=merge(s,j);render();if(!items.length)status.textContent=`No s'ha trobat cap resultat per «${q}».`}catch{status.textContent='No s’ha pogut consultar el cercador.'}}
form?.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();search(document.querySelector('#discoverSearch').value)},true);
document.querySelectorAll('.provider-chip').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.provider-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');provider=b.dataset.provider;render()}));
box?.addEventListener('click',async e=>{const b=e.target.closest('[data-v2-add]');if(!b)return;const m=box._v2Items?.[Number(b.dataset.v2Add)];if(!m)return;try{const r=await fetch('/api/movies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:m.title,year:m.year,genre:m.genre||null,poster_url:m.poster_url||null,movie_url:m.movie_url||null,streaming_urls:m.streaming_urls||{},description:m.description||null,duration_minutes:m.duration_minutes,rating:m.rating,notes:null,favorite:false,parent_movie_id:null,watched:false,watched_at:null})});if(!r.ok)throw Error();b.textContent='✓ Afegida';b.disabled=true}catch{b.textContent='Error'}});
new MutationObserver(m=>m.forEach(x=>x.addedNodes.forEach(n=>n.nodeType===1&&fixImages(n)))).observe(document.body,{childList:true,subtree:true});
fixImages();
})();
