(() => {
  const API='https://imdb.iamidiotareyoutoo.com/justwatch';
  const norm=s=>String(s??'').toLocaleLowerCase('ca').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const first=(o,keys)=>{for(const k of keys)if(o&&o[k]!=null&&typeof o[k]!=='object')return String(o[k]);return ''};
  const allStrings=(o,out=[])=>{if(o==null)return out;if(Array.isArray(o)){o.forEach(x=>allStrings(x,out));return out}if(typeof o!=='object')return out;for(const [k,v] of Object.entries(o)){if(typeof v==='string')out.push([k,v]);else if(v&&typeof v==='object')allStrings(v,out)}return out};
  const providerForUrl=url=>{try{const h=new URL(url).hostname.toLowerCase();if(h==='netflix.com'||h.endsWith('.netflix.com'))return'Netflix';if(h==='disneyplus.com'||h.endsWith('.disneyplus.com'))return'Disney+';if(h==='primevideo.com'||h.endsWith('.primevideo.com')||h==='amazon.com'||h.endsWith('.amazon.com'))return'Prime Video';if(h==='movistarplus.es'||h.endsWith('.movistarplus.es')||h==='movistar.es'||h.endsWith('.movistar.es'))return'Movistar Plus+'}catch{}return null};
  const providerNames=o=>{const text=JSON.stringify(o||{}).toLowerCase();const map={Netflix:['netflix','provider_id\\":8'],'Disney+':['disney+','disney plus','provider_id\\":337'],'Prime Video':['prime video','amazon video','provider_id\\":9'],'Movistar Plus+':['movistar','provider_id\\":149','provider_id\\":318']};return Object.keys(map).filter(p=>map[p].some(x=>text.includes(x)))};
  const streamingLinks=o=>{const found={};for(const [k,v] of allStrings(o)){if(!/^https?:\/\//i.test(v)||/\.(jpg|jpeg|png|webp|avif)(\?|$)/i.test(v))continue;const p=providerForUrl(v);if(p&&!found[p])found[p]=v}return found};
  const posterFrom=o=>{for(const [k,v] of allStrings(o)){if(/^https?:\/\//i.test(v)&&/(poster|image|thumbnail|cover)/i.test(k)&&/\.(jpg|jpeg|png|webp|avif)(\?|$)/i.test(v))return v}return''};
  const collect=(raw,q)=>{const roots=Array.isArray(raw)?raw:(raw?.items||raw?.results||raw?.data||raw?.titles||raw?.shows||raw?.movies||[raw]);const out=[],seen=new Set(),needle=norm(q);const walk=x=>{if(!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(walk);return}const title=first(x,['title','name','original_title','originalTitle']);if(title&&norm(title).includes(needle)){const year=first(x,['year','release_year','releaseYear','original_release_year']),key=(title+'|'+year).toLowerCase();if(!seen.has(key)){seen.add(key);const streaming_urls=streamingLinks(x);out.push({title,year,poster_url:posterFrom(x),streaming_urls,movie_url:Object.values(streaming_urls)[0]||'',genre:first(x,['genre','genres']),duration:first(x,['runtime','duration','runtime_minutes','duration_minutes']),providers:[...new Set([...providerNames(x),...Object.keys(streaming_urls)])]})}}Object.values(x).forEach(v=>v&&typeof v==='object'&&walk(v))};roots.forEach(walk);for(const m of out){const n=parseInt(String(m.duration??'').replace(/[^0-9]/g,''),10);m.duration=Number.isFinite(n)?n:null}return out};
  const render=(items,q)=>{const box=document.querySelector('#discoverResults'),status=document.querySelector('#discoverStatus');if(!items.length){box.innerHTML='';status.textContent=`No s'ha trobat cap resultat per «${q}».`;return}status.textContent=`${items.length} resultat${items.length===1?'':'s'}`;box.innerHTML=items.map((m,i)=>`<article class="discover-card"><div class="discover-poster">${m.poster_url?`<img src="${esc(m.poster_url)}" alt="Pòster de ${esc(m.title)}" loading="lazy">`:'<span>🎬</span>'}</div><div class="discover-info"><h3>${esc(m.title)}</h3><p>${esc(m.year||'Any desconegut')}${m.genre?` · ${esc(m.genre)}`:''}${m.duration?` · ${m.duration} min`:''}</p><div class="discover-providers">${m.providers.map(p=>`<span class="discover-provider">${esc(p)}</span>`).join('')}</div><div class="discover-actions">${m.movie_url?`<a class="secondary" href="${esc(m.movie_url)}" target="_blank" rel="noopener">🔗 Veure</a>`:''}<button class="primary" data-fix-add="${i}">+ Afegir a PeliTrack</button></div></div></article>`).join('');box._fixItems=items};
  const form=document.querySelector('#discoverForm');if(!form)return;
  form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const q=document.querySelector('#discoverSearch').value.trim();if(q.length<1)return;document.querySelector('#discoverStatus').textContent='Buscant…';try{const r=await fetch(`${API}?q=${encodeURIComponent(q)}&L=es_ES`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error();render(collect(await r.json(),q),q)}catch{document.querySelector('#discoverResults').innerHTML='';document.querySelector('#discoverStatus').textContent='No s’ha pogut fer la cerca.'}},true);
})();
