(() => {
  const JUSTWATCH_API='https://imdb.iamidiotareyoutoo.com/justwatch';
  const IMDB_API='https://v3.sg.media-imdb.com/suggestion/x/';
  const norm=s=>String(s??'').toLocaleLowerCase('ca').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const first=(o,keys)=>{for(const k of keys)if(o&&o[k]!=null&&typeof o[k]!=='object')return String(o[k]);return ''};
  const allStrings=(o,out=[])=>{if(o==null)return out;if(Array.isArray(o)){o.forEach(x=>allStrings(x,out));return out}if(typeof o!=='object')return out;for(const [k,v] of Object.entries(o)){if(typeof v==='string')out.push([k,v]);else if(v&&typeof v==='object')allStrings(v,out)}return out};
  const providerForUrl=url=>{try{const h=new URL(url).hostname.toLowerCase();if(h==='netflix.com'||h.endsWith('.netflix.com'))return'Netflix';if(h==='disneyplus.com'||h.endsWith('.disneyplus.com'))return'Disney+';if(h==='primevideo.com'||h.endsWith('.primevideo.com')||h==='amazon.com'||h.endsWith('.amazon.com'))return'Prime Video';if(h==='movistarplus.es'||h.endsWith('.movistarplus.es')||h==='movistar.es'||h.endsWith('.movistar.es'))return'Movistar Plus+'}catch{}return null};
  const providerNames=o=>{const text=JSON.stringify(o||{}).toLowerCase();const map={Netflix:['netflix','provider_id\\":8'],'Disney+':['disney+','disney plus','provider_id\\":337'],'Prime Video':['prime video','amazon video','provider_id\\":9'],'Movistar Plus+':['movistar','provider_id\\":149','provider_id\\":318']};return Object.keys(map).filter(p=>map[p].some(x=>text.includes(x)))};
  const streamingLinks=o=>{const found={};for(const [,v] of allStrings(o)){if(!/^https?:\/\//i.test(v)||/\.(jpg|jpeg|png|webp|avif)(\?|$)/i.test(v))continue;const p=providerForUrl(v);if(p&&!found[p])found[p]=v}return found};
  const posterFrom=o=>{for(const [k,v] of allStrings(o)){if(/^https?:\/\//i.test(v)&&/(poster|image|thumbnail|cover)/i.test(k)&&/\.(jpg|jpeg|png|webp|avif)(\?|$)/i.test(v))return v}return''};
  const imdbItems=raw=>(raw?.d||[]).filter(x=>x?.l).map(x=>({title:String(x.l),year:x.y?Number(x.y):null,poster_url:x?.i?.imageUrl||null,imdb_id:x.id||null}));
  const exactJustWatch=async title=>{try{const r=await fetch(`${JUSTWATCH_API}?q=${encodeURIComponent(title)}&L=es_ES`,{headers:{Accept:'application/json'}});if(!r.ok)return{};const raw=await r.json();const roots=Array.isArray(raw)?raw:(raw?.items||raw?.results||raw?.data||raw?.titles||raw?.shows||raw?.movies||[raw]);let found={};const walk=x=>{if(!x||typeof x!=='object'||found.title)return;if(Array.isArray(x)){x.forEach(walk);return}const t=first(x,['title','name','original_title','originalTitle']);if(t&&norm(t)===norm(title)){const urls=streamingLinks(x);found={title:t,year:first(x,['year','release_year','releaseYear']),genre:first(x,['genre','genres']),duration:first(x,['runtime','duration','runtime_minutes','duration_minutes']),providers:[...new Set([...providerNames(x),...Object.keys(urls)])],streaming_urls:urls,movie_url:Object.values(urls)[0]||'',poster_url:posterFrom(x)||null};return}Object.values(x).forEach(v=>v&&typeof v==='object'&&walk(v))};roots.forEach(walk);return found}catch{return{}}};
  const search=async q=>{const r=await fetch(`${IMDB_API}${encodeURIComponent(q)}.json`,{headers:{Accept:'application/json'}});if(!r.ok)throw Error();const items=imdbItems(await r.json());const seen=new Set();const base=items.filter(m=>{const k=(norm(m.title)+'|'+(m.year||''));if(seen.has(k))return false;seen.add(k);return norm(m.title).includes(norm(q))}).slice(0,30);const enriched=await Promise.all(base.map(async m=>({...m,...await exactJustWatch(m.title)})));return enriched.map(m=>({...m,poster_url:m.poster_url||null,providers:m.providers||[],streaming_urls:m.streaming_urls||{},movie_url:m.movie_url||null,year:m.year||null}))};
  const render=(items,q)=>{const box=document.querySelector('#discoverResults'),status=document.querySelector('#discoverStatus');if(!items.length){box.innerHTML='';status.textContent=`No s'ha trobat cap resultat per «${q}».`;return}status.textContent=`${items.length} resultat${items.length===1?'':'s'}`;box.innerHTML=items.map((m,i)=>`<article class="discover-card"><div class="discover-poster">${m.poster_url?`<img src="${esc(m.poster_url)}" alt="Pòster de ${esc(m.title)}" loading="lazy">`:'<span>🎬</span>'}</div><div class="discover-info"><h3>${esc(m.title)}</h3><p>${esc(m.year||'Any desconegut')}${m.genre?` · ${esc(m.genre)}`:''}${m.duration?` · ${esc(m.duration)} min`:''}</p><div class="discover-providers">${(m.providers||[]).map(p=>`<span class="discover-provider">${esc(p)}</span>`).join('')}</div><div class="discover-actions">${m.movie_url?`<a class="secondary" href="${esc(m.movie_url)}" target="_blank" rel="noopener">🔗 Veure</a>`:''}<button class="primary" data-fix-add="${i}">+ Afegir a PeliTrack</button></div></div></article>`).join('');box._fixItems=items};
  const form=document.querySelector('#discoverForm');if(!form)return;
  form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const q=document.querySelector('#discoverSearch').value.trim();if(q.length<1)return;document.querySelector('#discoverStatus').textContent='Buscant…';try{const items=await search(q);render(items,q)}catch{document.querySelector('#discoverResults').innerHTML='';document.querySelector('#discoverStatus').textContent='No s’ha pogut fer la cerca.'}},true);
  document.querySelector('#discoverResults')?.addEventListener('click',async e=>{const b=e.target.closest('[data-fix-add]');if(!b)return;const m=document.querySelector('#discoverResults')._fixItems?.[Number(b.dataset.fixAdd)];if(!m)return;try{const r=await fetch('/api/movies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:m.title,year:m.year,genre:m.genre||null,duration_minutes:m.duration?Number(String(m.duration).replace(/[^0-9]/g,'')):null,poster_url:m.poster_url||null,movie_url:m.movie_url||null,streaming_urls:m.streaming_urls||{},favorite:false,watched:false,watched_at:null,parent_movie_id:null})});if(!r.ok)throw Error();b.textContent='✓ Afegida';b.disabled=true}catch{b.textContent='Error'}});
})();
