const SUPABASE_URL='https://slyiyotaatewpgoylkbn.supabase.co';
const SUPABASE_KEY=['sb_publishable_','XVyAe1goGBo9TJ5k7UAn5g_rDbgTBnU'].join('');
const $=s=>document.querySelector(s),grid=$('#grid'),dialog=$('#dialog'); let movies=[],currentFilter='all';
const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2'); const db=createClient(SUPABASE_URL,SUPABASE_KEY);
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function poster(url,title){return url?`<img src="${escapeHtml(url)}" alt="Pòster de ${escapeHtml(title)}" loading="lazy" onerror="this.remove();this.parentElement.innerHTML='<span>🎬</span>'">`:'<span>🎬</span>'}
function lastWatched(m){return m.last_watched_at?new Date(m.last_watched_at).getTime():0}
function dateTimeText(m){if(!m.last_watched_at)return 'Encara no vista';const d=new Date(m.last_watched_at);return `Vista: ${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()} · ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function isFirst(m){return !m.parent_movie_id}
function movieNumber(m){if(isFirst(m))return 1;const siblings=movies.filter(x=>String(x.parent_movie_id)===String(m.parent_movie_id)).sort((a,b)=>(a.year||9999)-(b.year||9999)||String(a.title).localeCompare(String(b.title),'ca')||String(a.id).localeCompare(String(b.id)));return siblings.findIndex(x=>String(x.id)===String(m.id))+2}
function seriesInfo(m){const parent=movies.find(x=>String(x.id)===String(m.parent_movie_id));if(!parent)return '<div class="series-badge main-series">🎬 <strong>1a de la saga</strong></div>';return `<div class="series-badge continuation-series">🔗 <strong>${movieNumber(m)}a de la saga</strong><span> · ${escapeHtml(parent.title)}</span></div>`}
function visibleMovies(){const q=$('#search').value.trim().toLowerCase();let list=movies.filter(m=>{if(q&&!`${m.title||''} ${m.description||''}`.toLowerCase().includes(q))return false;if(currentFilter==='pending'&&m.watched)return false;if(currentFilter==='watched'&&!m.watched)return false;if(currentFilter==='favorite'&&!m.favorite)return false;return true});const s=$('#sort').value;list.sort((a,b)=>s==='title'?String(a.title).localeCompare(String(b.title),'ca'):s==='year-desc'?(b.year||0)-(a.year||0):s==='year-asc'?(a.year||9999)-(b.year||9999):s==='last-watched-asc'?(lastWatched(a)||0)-(lastWatched(b)||0):(b.rating||0)-(a.rating||0));return list}
function card(m){return `<article class="card"><div class="poster">${poster(m.poster_url,m.title)}</div><div class="card-body"><h3 title="${escapeHtml(m.title)}">${escapeHtml(m.title)}</h3>${seriesInfo(m)}<div class="meta">${m.year||'—'} · ⭐ ${m.rating??'—'}</div><div class="badges"><span class="badge">${m.watched?'✓ '+dateTimeText(m):'Pendent'}</span>${m.favorite?'<span class="badge">❤️</span>':''}</div><div class="card-actions"><button data-action="watched" data-id="${m.id}">Vista</button><button data-action="edit" data-id="${m.id}">Editar</button><button data-action="delete" data-id="${m.id}">🗑️</button></div></div></article>`}
function render(){const list=visibleMovies();$('#total').textContent=movies.length;$('#watched').textContent=movies.filter(m=>m.watched).length;$('#pending').textContent=movies.filter(m=>!m.watched).length;grid.innerHTML=list.map(card).join('');$('#empty').classList.toggle('hidden',list.length>0);grid.classList.toggle('hidden',list.length===0)}
function populateParentMovies(currentId=''){const select=$('#parentMovie');const options=movies.filter(m=>String(m.id)!==String(currentId)&&isFirst(m)).sort((a,b)=>String(a.title).localeCompare(String(b.title),'ca'));select.innerHTML='<option value="">🎬 Primera pel·lícula de la saga</option>'+options.map(m=>`<option value="${m.id}">${escapeHtml(m.title)}${m.year?` (${m.year})`:''}</option>`).join('')}
function formMovie(m={}){$('#modalTitle').textContent=m.id?'Editar pel·lícula':'Afegir pel·lícula';$('#id').value=m.id||'';$('#title').value=m.title||'';$('#year').value=m.year||'';$('#genreInput').value=m.genre||'';$('#duration').value=m.duration_minutes||'';$('#rating').value=m.rating??'';$('#poster').value=m.poster_url||'';$('#description').value=m.description||'';$('#notes').value=m.notes||'';$('#isFavorite').checked=!!m.favorite;populateParentMovies(m.id||'');$('#parentMovie').value=m.parent_movie_id?String(m.parent_movie_id):'';dialog.showModal();$('#title').focus()}
function readForm(){return{title:$('#title').value.trim(),year:$('#year').value?Number($('#year').value):null,genre:$('#genreInput').value.trim()||null,duration_minutes:$('#duration').value?Number($('#duration').value):null,rating:$('#rating').value?Number($('#rating').value):null,poster_url:$('#poster').value.trim()||null,description:$('#description').value.trim()||null,notes:$('#notes').value.trim()||null,favorite:$('#isFavorite').checked,parent_movie_id:$('#parentMovie').value?Number($('#parentMovie').value):null,updated_at:new Date().toISOString()}}
function notify(message,type='ok'){let n=document.querySelector('.toast');if(n)n.remove();n=document.createElement('div');n.className=`toast ${type}`;n.setAttribute('role','status');n.textContent=message;document.body.appendChild(n);requestAnimationFrame(()=>n.classList.add('show'));setTimeout(()=>{n.classList.remove('show');setTimeout(()=>n.remove(),250)},3000)}
async function load(){const {data,error}=await db.from('movies').select('*').order('title');if(error){console.error(error);notify('No s’han pogut carregar les pel·lícules.','error');return}movies=data||[];render()}
async function createMovie(m){const movie={...m,watched:false,last_watched_at:null};const {data,error}=await db.from('movies').insert(movie).select().single();if(error)throw error;movies.push(data)}
async function updateMovie(id,m){const {data,error}=await db.from('movies').update(m).eq('id',id).select().single();if(error)throw error;movies=movies.map(x=>String(x.id)===String(id)?data:x)}
async function removeMovie(id){const {error}=await db.from('movies').delete().eq('id',id);if(error)throw error;movies=movies.filter(x=>String(x.id)!==String(id))}
function randomPick(){const firstMovies=movies.filter(isFirst);if(firstMovies.length<5){notify('Necessites almenys 5 pel·lícules principals.','error');return}const ranked=[...firstMovies].sort((a,b)=>(lastWatched(a)||0)-(lastWatched(b)||0));const first=ranked.slice(0,3),used=new Set(first.map(m=>String(m.id))),rest=firstMovies.filter(m=>!used.has(String(m.id))).sort(()=>Math.random()-.5),picks=[...first];while(picks.length<5&&rest.length)picks.push(rest.shift());$('#randomGrid').innerHTML=picks.map(card).join('');$('#randomPanel').classList.remove('hidden')}
$('#addBtn').onclick=()=>formMovie();$('#emptyAdd').onclick=()=>formMovie();$('#close').onclick=()=>dialog.close();$('#cancel').onclick=()=>dialog.close();$('#randomBtn').onclick=randomPick;$('#closeRandom').onclick=()=>$('#randomPanel').classList.add('hidden');
$('#form').addEventListener('submit',async e=>{e.preventDefault();const id=$('#id').value,m=readForm();if(!m.title)return;try{if(id){await updateMovie(id,m);notify('Pel·lícula actualitzada ✓')}else{await createMovie(m);notify('Pel·lícula afegida ✓')}render();dialog.close()}catch(err){console.error(err);notify('Error en guardar la pel·lícula','error')}});
async function handleClick(e){const b=e.target.closest('button');if(!b)return;const m=movies.find(x=>String(x.id)===String(b.dataset.id));if(!m)return;try{if(b.dataset.action==='edit')return formMovie(m);if(b.dataset.action==='watched'){const now=new Date().toISOString();const watchedMovie={...m,last_watched_at:now,watched:true};await updateMovie(m.id,{watched:true,last_watched_at:now,updated_at:now});notify(`«${m.title}» actualitzada com a vista ✓ · ${dateTimeText(watchedMovie)}`)}if(b.dataset.action==='delete'&&confirm(`Eliminar «${m.title}»?`)){await removeMovie(m.id);notify('Pel·lícula eliminada ✓')}render()}catch(err){console.error(err);notify('No s’ha pogut completar l’acció','error')}}
grid.addEventListener('click',handleClick);$('#randomGrid').addEventListener('click',handleClick);document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()});$('#search').oninput=render;$('#sort').onchange=render;load();