const $=s=>document.querySelector(s),grid=$('#grid'),dialog=$('#dialog'),detailDialog=$('#detailDialog'),discoverDialog=$('#discoverDialog');
let movies=[],currentFilter='all',discoverItems=[],discoverProvider='all';
const API='/api/movies';
const DISCOVER_API='https://imdb.iamidiotareyoutoo.com/justwatch';
const DISCOVER_PROVIDERS=['Netflix','Disney+','Prime Video','Movistar Plus+'];
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function isDisneyUrl(url=''){try{return /(^|\.)disneyplus\.com$/i.test(new URL(url).hostname)}catch{return false}}
function imageSource(url){return url?(isDisneyUrl(url)?`/api/disney-poster?url=${encodeURIComponent(url)}`:url):''}
function poster(url,title){const src=imageSource(url);return src?`<img src="${escapeHtml(src)}" alt="Pòster de ${escapeHtml(title)}" loading="lazy" onerror="this.onerror=null;this.remove();this.parentElement.innerHTML='<span>🎬</span>'">`:'<span>🎬</span>'}
function watchedTime(m){return m.watched_at?new Date(m.watched_at).getTime():0}
function dateTimeText(m){if(!m.watched_at)return 'Encara no vista';const d=new Date(m.watched_at);return `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()} · ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function isFirst(m){return !m.parent_movie_id}
function movieNumber(m){if(isFirst(m))return 1;const siblings=movies.filter(x=>String(x.parent_movie_id)===String(m.parent_movie_id)).sort((a,b)=>(a.year||9999)-(b.year||9999)||String(a.title).localeCompare(String(b.title),'ca')||Number(a.id)-Number(b.id));return siblings.findIndex(x=>String(x.id)===String(m.id))+2}
function seriesInfo(m){const parent=movies.find(x=>String(x.id)===String(m.parent_movie_id));return parent?`<div class="series-badge continuation-series">🔗 <strong>${movieNumber(m)}a de la saga</strong><span> · ${escapeHtml(parent.title)}</span></div>`:'<div class="series-badge main-series">🎬 <strong>1a de la saga</strong></div>'}
function genreList(){const values=[...new Set(movies.flatMap(m=>String(m.genre||'').split(',').map(x=>x.trim()).filter(Boolean)))].sort((a,b)=>a.localeCompare(b,'ca')),current=$('#genre').value;$('#genre').innerHTML='<option value="">Tots els gèneres</option>'+values.map(g=>`<option value="${escapeHtml(g)}">${escapeHtml(g)}</option>`).join('');if(values.includes(current))$('#genre').value=current}
function visibleMovies(){const q=$('#search').value.trim().toLowerCase(),genre=$('#genre').value;let list=movies.filter(m=>{if(q&&!String(m.title||'').toLowerCase().includes(q))return false;if(genre&&!String(m.genre||'').split(',').map(x=>x.trim()).includes(genre))return false;if(currentFilter==='favorite'&&!m.favorite)return false;return true});const s=$('#sort').value;list.sort((a,b)=>s==='title'?String(a.title).localeCompare(String(b.title),'ca'):s==='year-desc'?(b.year||0)-(a.year||0):s==='year-asc'?(a.year||9999)-(b.year||9999):s==='last-watched-desc'?watchedTime(b)-watchedTime(a):s==='last-watched-asc'?watchedTime(a)-watchedTime(b):(b.rating||0)-(a.rating||0));return list}
function card(m){return `<article class="card" data-open="${m.id}"><div class="poster">${poster(m.poster_url,m.title)}</div><div class="card-body"><h3 title="${escapeHtml(m.title)}">${escapeHtml(m.title)}</h3>${seriesInfo(m)}<div class="meta">${m.year||'—'}${m.rating!=null?` · ⭐ ${m.rating}/10`:''}</div><div class="badges"><span class="badge">${m.watched?'✓ Vista: '+dateTimeText(m):'Pendent'}</span>${m.favorite?'<span class="badge">♥</span>':''}</div><div class="card-actions"><button data-action="watched" data-id="${m.id}">Vista</button><button data-action="favorite" data-id="${m.id}" aria-label="${m.favorite?'Treure de favorites':'Afegir a favorites'}">${m.favorite?'♥':'♡'}</button><button data-action="edit" data-id="${m.id}">Editar</button><button data-action="delete" data-id="${m.id}">🗑️</button></div></div></article>`}
function render(){const list=visibleMovies();$('#total').textContent=movies.length;grid.innerHTML=list.map(card).join('');$('#empty').classList.toggle('hidden',list.length>0);grid.classList.toggle('hidden',list.length===0);genreList()}
function populateParentMovies(currentId=''){const select=$('#parentMovie'),options=movies.filter(m=>String(m.id)!==String(currentId)&&isFirst(m)).sort((a,b)=>String(a.title).localeCompare(String(b.title),'ca'));select.innerHTML='<option value="">🎬 Primera pel·lícula de la saga</option>'+options.map(m=>`<option value="${m.id}">${escapeHtml(m.title)}${m.year?` (${m.year})`:''}</option>`).join('')}
function formMovie(m={}){$('#modalTitle').textContent=m.id?'Editar pel·lícula':'Afegir pel·lícula';$('#id').value=m.id||'';$('#title').value=m.title||'';$('#year').value=m.year||'';$('#genreInput').value=m.genre||'';$('#duration').value=m.duration_minutes||'';$('#rating').value=m.rating??'';$('#poster').value=m.poster_url||'';$('#description').value=m.description||'';$('#notes').value=m.notes||'';$('#isFavorite').checked=!!m.favorite;populateParentMovies(m.id||'');$('#parentMovie').value=m.parent_movie_id?String(m.parent_movie_id):'';dialog.showModal();$('#title').focus()}
function readForm(){const rating=$('#rating').value?Number($('#rating').value):null;return{title:$('#title').value.trim(),year:$('#year').value?Number($('#year').value):null,genre:$('#genreInput').value.trim()||null,duration_minutes:$('#duration').value?Number($('#duration').value):null,rating:rating!=null?Math.max(0,Math.min(10,rating)):null,poster_url:$('#poster').value.trim()||null,description:$('#description').value.trim()||null,notes:$('#notes').value.trim()||null,favorite:$('#isFavorite').checked,parent_movie_id:$('#parentMovie').value?Number($('#parentMovie').value):null}}
function notify(message,type='ok'){let n=document.querySelector('.toast');if(n)n.remove();n=document.createElement('div');n.className=`toast ${type}`;n.setAttribute('role','status');n.textContent=message;document.body.appendChild(n);requestAnimationFrame(()=>n.classList.add('show'));setTimeout(()=>{n.classList.remove('show');setTimeout(()=>n.remove(),250)},2800)}
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!r.ok){let e={};try{e=await r.json()}catch{}throw new Error(e.error||`HTTP ${r.status}`)}return r.status===204?null:r.json()}
async function load(){try{movies=await api(API);render()}catch(e){console.error(e);notify('No s’han pogut carregar les pel·lícules.','error')}}
async function createMovie(m){const data=await api(API,{method:'POST',body:JSON.stringify(m)});movies.push(data);return data}
async function updateMovie(id,m){const data=await api(`${API}/${id}`,{method:'PATCH',body:JSON.stringify(m)});movies=movies.map(x=>String(x.id)===String(id)?data:x);return data}
async function removeMovie(id){await api(`${API}/${id}`,{method:'DELETE'});movies=movies.filter(x=>String(x.id)!==String(id))}
function randomPick(){const firstMovies=movies.filter(isFirst);if(firstMovies.length<5){notify('Necessites almenys 5 pel·lícules principals.','error');return}const ranked=[...firstMovies].sort((a,b)=>watchedTime(a)-watchedTime(b)),first=ranked.slice(0,3),used=new Set(first.map(m=>String(m.id))),rest=firstMovies.filter(m=>!used.has(String(m.id))).sort(()=>Math.random()-.5),picks=[...first];while(picks.length<5&&rest.length)picks.push(rest.shift());$('#randomGrid').innerHTML=picks.map(card).join('');$('#randomPanel').classList.remove('hidden')}
function detailMovie(m){$('#detailTitle').textContent=m.title;$('#detailContent').innerHTML=`<div class="detail-grid"><div class="detail-poster">${poster(m.poster_url,m.title)}</div><div class="detail-info">${seriesInfo(m)}<p class="detail-meta">${m.year||'Any desconegut'}${m.genre?` · ${escapeHtml(m.genre)}`:''}${m.duration_minutes?` · ${m.duration_minutes} min`:''}</p><div class="detail-rating">${m.rating!=null?`⭐ ${m.rating}/10`:'Sense puntuació'}</div><p>${escapeHtml(m.description||'Sense descripció.')}</p>${m.notes?`<p><strong>Notes:</strong> ${escapeHtml(m.notes)}</p>`:''}<p class="detail-status">${m.watched?'✓ Vista · '+dateTimeText(m):'○ Pendent'}</p><div class="detail-actions"><button class="primary" data-detail="watched" data-id="${m.id}">${m.watched?'No vista':'Vista'}</button><button class="secondary" data-detail="favorite" data-id="${m.id}">${m.favorite?'♥ Favorita':'♡ Afegir a favorites'}</button><button class="secondary" data-detail="edit" data-id="${m.id}">Editar</button><button class="secondary danger" data-detail="delete" data-id="${m.id}">Eliminar</button></div></div></div>`;detailDialog.showModal()}

function firstString(obj,keys){if(!obj||typeof obj!=='object')return '';for(const key of keys){if(obj[key]!=null&&typeof obj[key]!=='object')return String(obj[key])}return ''}
function collectStrings(obj,keys,out=[]){if(obj==null)return out;if(Array.isArray(obj)){obj.forEach(x=>collectStrings(x,keys,out));return out}if(typeof obj!=='object')return out;for(const [k,v] of Object.entries(obj)){if(keys.some(x=>k.toLowerCase().includes(x))&&typeof v==='string')out.push(v);else if(typeof v==='object')collectStrings(v,keys,out)}return out}
function knownProviders(obj){const text=collectStrings(obj,['provider','service','source','name','clear_name']).join(' | ').toLowerCase();return DISCOVER_PROVIDERS.filter(p=>text.includes(p.toLowerCase())||text.includes(p==='Prime Video'?'amazon video':'__never__'))}
function posterFrom(obj){const candidates=['poster_url','posterUrl','poster','image_url','imageUrl','image','thumbnail'];for(const k of candidates){const v=firstString(obj,[k]);if(v&&/^https?:\/\//i.test(v))return v}return ''}
function normalizeDiscover(raw){let roots=Array.isArray(raw)?raw:(raw?.items||raw?.results||raw?.data||raw?.titles||raw?.shows||raw?.movies||[raw]);const out=[];const seen=new Set();function walk(x){if(!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(walk);return}const title=firstString(x,['title','name','original_title','originalTitle']);if(title){const providers=knownProviders(x);const year=firstString(x,['year','release_year','releaseYear','original_release_year']);const imdb=firstString(x,['imdb_id','imdbId']);const key=(imdb||title+'|'+year).toLowerCase();if(!seen.has(key)){seen.add(key);out.push({title,year:year?Number(year):null,genre:firstString(x,['genre','genres']),poster_url:posterFrom(x),description:firstString(x,['description','overview','plot','synopsis']),duration_minutes:Number(firstString(x,['runtime','duration','runtime_minutes']))||null,rating:Number(firstString(x,['rating','score','vote_average']))||null,providers})}}Object.values(x).forEach(v=>{if(v&&typeof v==='object')walk(v)})}roots.forEach(walk);return out}
function providerBadge(name){const icons={'Netflix':'🔴','Disney+':'🔵','Prime Video':'🔷','Movistar Plus+':'🟢'};return `<span class="discover-provider">${icons[name]||'▶️'} ${escapeHtml(name)}</span>`}
function renderDiscover(){const list=discoverProvider==='all'?discoverItems:discoverItems.filter(m=>m.providers.includes(discoverProvider));const box=$('#discoverResults');if(!list.length){box.innerHTML='';$('#discoverStatus').textContent=discoverItems.length?'Cap de les pel·lis trobades està disponible al filtre seleccionat.':'No s’han trobat pel·lícules.';return}$('#discoverStatus').textContent=`${list.length} resultat${list.length===1?'':'s'} trobats`;box.innerHTML=list.slice(0,30).map((m,i)=>`<article class="discover-card"><div class="discover-poster">${poster(m.poster_url,m.title)}</div><div class="discover-info"><h3>${escapeHtml(m.title)}</h3><p>${m.year||'Any desconegut'}${m.rating?` · ⭐ ${m.rating.toFixed(1)}/10`:''}</p><div class="discover-providers">${m.providers.length?m.providers.map(providerBadge).join(''):'<span class="discover-none">Disponibilitat no indicada</span>'}</div><div class="discover-actions"><button class="primary" data-discover-add="${i}">+ Afegir a PeliTrack</button></div></div></article>`).join('')}
async function searchDiscover(query){$('#discoverStatus').textContent='Buscant…';$('#discoverResults').innerHTML='';try{const r=await fetch(`${DISCOVER_API}?q=${encodeURIComponent(query)}&L=es_ES`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const raw=await r.json();discoverItems=normalizeDiscover(raw);renderDiscover()}catch(e){console.error(e);discoverItems=[];$('#discoverStatus').textContent='No s’ha pogut consultar el cercador ara mateix. Torna-ho a provar.'}}
async function addDiscoverMovie(index){const m=(discoverProvider==='all'?discoverItems:discoverItems.filter(x=>x.providers.includes(discoverProvider)))[index];if(!m)return;try{await createMovie({title:m.title,year:m.year,genre:m.genre||null,poster_url:m.poster_url||null,description:m.description||null,duration_minutes:m.duration_minutes,rating:m.rating!=null?Math.max(0,Math.min(10,m.rating)):null,notes:null,favorite:false,parent_movie_id:null,watched:false,watched_at:null});render();notify(`«${m.title}» afegida a PeliTrack ✓`)}catch(e){console.error(e);notify('No s’ha pogut afegir la pel·lícula','error')}}

$('#addBtn').onclick=()=>formMovie();$('#emptyAdd').onclick=()=>formMovie();$('#close').onclick=()=>dialog.close();$('#cancel').onclick=()=>dialog.close();$('#randomBtn').onclick=randomPick;$('#closeRandom').onclick=()=>$('#randomPanel').classList.add('hidden');$('#closeDetail').onclick=()=>detailDialog.close();
$('#discoverBtn').onclick=()=>{discoverDialog.showModal();$('#discoverSearch').focus()};$('#closeDiscover').onclick=()=>discoverDialog.close();
$('#discoverForm').addEventListener('submit',async e=>{e.preventDefault();const q=$('#discoverSearch').value.trim();if(q)await searchDiscover(q)});
document.querySelectorAll('.provider-chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.provider-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');discoverProvider=b.dataset.provider;renderDiscover()});
$('#discoverResults').addEventListener('click',e=>{const b=e.target.closest('[data-discover-add]');if(!b)return;addDiscoverMovie(Number(b.dataset.discoverAdd))});
$('#form').addEventListener('submit',async e=>{e.preventDefault();const id=$('#id').value,m=readForm();if(!m.title)return;try{if(id){await updateMovie(id,m);notify('Pel·lícula actualitzada ✓')}else{await createMovie(m);notify('Pel·lícula afegida ✓')}render();dialog.close()}catch(err){console.error(err);notify('No s’ha pogut guardar la pel·lícula','error')}});
async function markWatched(id){await updateMovie(id,{watched:true,watched_at:new Date().toISOString()});notify('Marcada com a vista ✓')}
async function markUnwatched(id){await updateMovie(id,{watched:false,watched_at:null});notify('Marcada com a pendent ✓')}
async function toggleFavorite(id){const m=movies.find(x=>String(x.id)===String(id));if(!m)return;await updateMovie(id,{favorite:!m.favorite});notify(!m.favorite?'Afegida a favorites ✓':'Treta de favorites ✓')}
async function deleteMovie(id){const m=movies.find(x=>String(x.id)===String(id));if(!m||!confirm(`Eliminar «${m.title}»?`))return;await removeMovie(id);detailDialog.close();notify('Pel·lícula eliminada ✓')}
async function handleClick(e){const b=e.target.closest('button');if(b){const id=b.dataset.id;try{if(b.dataset.action==='watched')await markWatched(id);else if(b.dataset.action==='favorite')await toggleFavorite(id);else if(b.dataset.action==='edit')return formMovie(movies.find(x=>String(x.id)===String(id)));else if(b.dataset.action==='delete')await deleteMovie(id);render()}catch(err){console.error(err);notify('No s’ha pogut completar l’acció','error')}return}const c=e.target.closest('.card');if(c){const m=movies.find(x=>String(x.id)===String(c.dataset.open));if(m)detailMovie(m)}}
async function handleDetail(e){const b=e.target.closest('button[data-detail]');if(!b)return;const id=b.dataset.id;try{if(b.dataset.detail==='watched'){const m=movies.find(x=>String(x.id)===String(id));if(m?.watched)await markUnwatched(id);else await markWatched(id)}else if(b.dataset.detail==='favorite')await toggleFavorite(id);else if(b.dataset.detail==='edit'){detailDialog.close();return formMovie(movies.find(x=>String(x.id)===String(id)))}else if(b.dataset.detail==='delete')await deleteMovie(id);const m=movies.find(x=>String(x.id)===String(id));if(m)detailMovie(m);render()}catch(err){console.error(err);notify('No s’ha pogut completar l’acció','error')}}
grid.addEventListener('click',handleClick);$('#randomGrid').addEventListener('click',handleClick);$('#detailContent').addEventListener('click',handleDetail);
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()});
$('#search').oninput=render;$('#genre').onchange=render;$('#sort').onchange=render;load();
