const SUPABASE_URL='https://slyiyotaatewpgoylkbn.supabase.co';
const SUPABASE_KEY=['sb_publishable_','XVyAe1goGBo9TJ5k7UAn5g_rDbgTBnU'].join('');
const $=s=>document.querySelector(s),grid=$('#grid'),dialog=$('#dialog');
let movies=[],currentFilter='all';
const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2');
const db=createClient(SUPABASE_URL,SUPABASE_KEY);
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function poster(url,title){return url?`<img src="${escapeHtml(url)}" alt="Pòster de ${escapeHtml(title)}" loading="lazy" onerror="this.remove();this.parentElement.innerHTML='<span>🎬</span>'">`:'<span>🎬</span>'}
function lastWatched(m){return m.last_watched_at?new Date(m.last_watched_at).getTime():0}
function daysSince(m){if(!m.last_watched_at)return Infinity;return Math.max(0,Math.floor((Date.now()-lastWatched(m))/86400000))}
function dateText(m){return m.watched&&m.last_watched_at?`Vista fa ${daysSince(m)} ${daysSince(m)===1?'dia':'dies'}`:'No vista'}
function visibleMovies(){const q=$('#search').value.trim().toLowerCase(),g=$('#genre').value;let list=movies.filter(m=>{if(q&&!`${m.title||''} ${m.genre||''} ${m.description||''}`.toLowerCase().includes(q))return false;if(g&&m.genre!==g)return false;if(currentFilter==='pending'&&m.watched)return false;if(currentFilter==='watched'&&!m.watched)return false;if(currentFilter==='favorite'&&!m.favorite)return false;return true});const s=$('#sort').value;list.sort((a,b)=>s==='title'?String(a.title).localeCompare(String(b.title),'ca'):s==='year-desc'?(b.year||0)-(a.year||0):s==='year-asc'?(a.year||9999)-(b.year||9999):s==='last-watched-asc'?lastWatched(a)-lastWatched(b):(b.rating||0)-(a.rating||0));return list}
function card(m){return `<article class="card"><div class="poster">${poster(m.poster_url,m.title)}</div><div class="card-body"><h3 title="${escapeHtml(m.title)}">${escapeHtml(m.title)}</h3><div class="meta">${m.year||'—'} · ${escapeHtml(m.genre||'Sense gènere')} · ⭐ ${m.rating??'—'}</div><div class="badges"><span class="badge">${m.watched?'✓ '+dateText(m):'Pendent'}</span>${m.favorite?'<span class="badge">❤️</span>':''}</div><div class="card-actions"><button data-action="watched" data-id="${m.id}">Vista</button><button data-action="edit" data-id="${m.id}">Editar</button><button data-action="delete" data-id="${m.id}">🗑️</button></div></div></article>`}
function render(){const list=visibleMovies();$('#total').textContent=movies.length;$('#watched').textContent=movies.filter(m=>m.watched).length;$('#pending').textContent=movies.filter(m=>!m.watched).length;grid.innerHTML=list.map(card).join('');$('#empty').classList.toggle('hidden',list.length>0);grid.classList.toggle('hidden',list.length===0)}
function populateGenres(){const current=$('#genre').value,genres=[...new Set(movies.map(m=>m.genre).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ca'));$('#genre').innerHTML='<option value="">Tots els gèneres</option>'+genres.map(g=>`<option value="${escapeHtml(g)}">${escapeHtml(g)}</option>`).join('');$('#genre').value=genres.includes(current)?current:''}
function formMovie(m={}){$('#modalTitle').textContent=m.id?'Editar pel·lícula':'Afegir pel·lícula';$('#id').value=m.id||'';$('#title').value=m.title||'';$('#year').value=m.year||'';$('#genreInput').value=m.genre||'';$('#duration').value=m.duration_minutes||'';$('#rating').value=m.rating??'';$('#poster').value=m.poster_url||'';$('#description').value=m.description||'';$('#notes').value=m.notes||'';$('#isFavorite').checked=!!m.favorite;dialog.showModal();$('#title').focus()}
function readForm(){return{title:$('#title').value.trim(),year:$('#year').value?Number($('#year').value):null,genre:$('#genreInput').value.trim()||null,duration_minutes:$('#duration').value?Number($('#duration').value):null,rating:$('#rating').value?Number($('#rating').value):null,poster_url:$('#poster').value.trim()||null,description:$('#description').value.trim()||null,notes:$('#notes').value.trim()||null,favorite:$('#isFavorite').checked,updated_at:new Date().toISOString()}}
async function load(){const {data,error}=await db.from('movies').select('*').order('title');if(error){console.error(error);alert('No s’han pogut carregar les pel·lícules.');return}movies=data||[];populateGenres();render()}
async function createMovie(m){const movie={...m,watched:false,last_watched_at:null};const {data,error}=await db.from('movies').insert(movie).select().single();if(error)throw error;movies.push(data)}
async function updateMovie(id,m){const {data,error}=await db.from('movies').update(m).eq('id',id).select().single();if(error)throw error;movies=movies.map(x=>String(x.id)===String(id)?data:x)}
async function removeMovie(id){const {error}=await db.from('movies').delete().eq('id',id);if(error)throw error;movies=movies.filter(x=>String(x.id)!==String(id))}
function randomPick(){if(movies.length<5){alert('Necessites almenys 5 pel·lícules.');return}const ranked=[...movies].sort((a,b)=>lastWatched(a)-lastWatched(b));const first=ranked.slice(0,3);const used=new Set(first.map(m=>String(m.id)));const rest=movies.filter(m=>!used.has(String(m.id))).sort(()=>Math.random()-.5);const picks=[...first];while(picks.length<5&&rest.length)picks.push(rest.shift());$('#randomGrid').innerHTML=picks.map(card).join('');$('#randomPanel').classList.remove('hidden')}
$('#addBtn').onclick=()=>formMovie();$('#emptyAdd').onclick=()=>formMovie();$('#close').onclick=()=>dialog.close();$('#cancel').onclick=()=>dialog.close();$('#randomBtn').onclick=randomPick;$('#closeRandom').onclick=()=>$('#randomPanel').classList.add('hidden');
$('#form').addEventListener('submit',async e=>{e.preventDefault();const id=$('#id').value,m=readForm();if(!m.title)return;try{if(id)await updateMovie(id,m);else await createMovie(m);populateGenres();render();dialog.close()}catch(err){console.error(err);alert('Error en guardar la pel·lícula: '+(err.message||'error desconegut'))}});
async function handleClick(e){const b=e.target.closest('button');if(!b)return;const m=movies.find(x=>String(x.id)===String(b.dataset.id));if(!m)return;try{if(b.dataset.action==='edit')return formMovie(m);if(b.dataset.action==='watched'){if(m.watched)return;await updateMovie(m.id,{watched:true,last_watched_at:new Date().toISOString(),updated_at:new Date().toISOString()})}if(b.dataset.action==='delete'&&confirm(`Eliminar «${m.title}»?`))await removeMovie(m.id);populateGenres();render()}catch(err){console.error(err);alert('No s’ha pogut completar l’acció: '+(err.message||'error desconegut'))}}
grid.addEventListener('click',handleClick);$('#randomGrid').addEventListener('click',handleClick);document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()});$('#search').oninput=render;$('#genre').onchange=render;$('#sort').onchange=render;load();