(() => {
  const API='https://imdb.iamidiotareyoutoo.com/justwatch';
  const providers=['Netflix','Disney+','Prime Video','Movistar Plus+'];
  const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const exact=(q,t)=>norm(q)===norm(t);
  const first=(o,keys)=>{for(const k of keys)if(o&&o[k]!=null&&typeof o[k]!=='object')return String(o[k]);return ''};
  const find=(o,hints)=>{let result=null;const walk=x=>{if(result!==null||!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(walk);return}for(const [k,v] of Object.entries(x)){if(result!==null)break;const key=k.toLowerCase();if(hints.some(h=>key.includes(h))&&(typeof v==='string'||typeof v==='number'))result=v;else if(v&&typeof v==='object')walk(v)}};walk(o);return result};
  const poster=o=>{for(const k of ['poster_url','posterUrl','poster','image_url','imageUrl','image','thumbnail']){const v=first(o,[k]);if(/^https?:\/\//i.test(v))return v}return ''};
  const genres=o=>{const g=find(o,['genre','genres']);if(Array.isArray(g))return g.map(x=>typeof x==='string'?x:first(x,['name','title'])).filter(Boolean).join(', ');return g?String(g):''};
  const duration=o=>{const v=find(o,['runtime','duration','runtime_minutes','duration_minutes']);if(v==null)return null;const n=parseInt(String(v).replace(/[^0-9]/g,''),10);return Number.isFinite(n)?n:null};
  const providerNames=o=>{const text=JSON.stringify(o||{}).toLowerCase();const map={Netflix:['netflix','provider_id":8'], 'Disney+':['disney+','disney plus','provider_id":337'], 'Prime Video':['prime video','amazon video','provider_id":9'], 'Movistar Plus+':['movistar','provider_id":149','provider_id":318']};return providers.filter(p=>map[p].some(x=>text.includes(x)))};
  function collect(raw,q){const roots=Array.isArray(raw)?raw:(raw?.items||raw?.results||raw?.data||raw?.titles||raw?.shows||raw?.movies||[raw]);const out=[],seen=new Set();const walk=x=>{if(!x||typeof x!=='object'||out.length>=1)return;if(Array.isArray(x)){for(const v of x){walk(v);if(out.length>=1)break}return}const title=first(x,['title','name','original_title','originalTitle']);if(title&&exact(q,title)){const year=first(x,['year','release_year','releaseYear','original_release_year']),key=(first(x,['imdb_id','imdbId'])||norm(title)+'|'+year).toLowerCase();if(!seen.has(key)){seen.add(key);out.push({title,year,poster:poster(x),genre:genres(x),duration:duration(x),providers:providerNames(x)})}}if(out.length<1)Object.values(x).forEach(v=>v&&typeof v==='object'&&out.length<1&&walk(v))};roots.forEach(walk);return out.slice(0,1)}
  const render=(items,q)=>{const box=document.querySelector('#discoverResults'),status=document.querySelector('#discoverStatus');if(!items.length){box.innerHTML='';status.textContent=`No s'ha trobat «${q}».`;return}status.textContent='1 resultat';box.innerHTML=items.map((m,i)=>`<article class="discover-card"><div class="discover-poster">${m.poster?`<img src="${esc(m.poster)}" alt="Pòster de ${esc(m.title)}" loading="lazy">`:'<span>🎬</span>'}</div><div class="discover-info"><h3>${esc(m.title)}</h3><p>${esc(m.year||'Any desconegut')}${m.genre?` · ${esc(m.genre)}`:''}${m.duration?` · ${m.duration} min`:''}</p><div class="discover-providers">${m.providers.map(p=>`<span class="discover-provider">${esc(p)}</span>`).join('')}</div><div class="discover-actions"><button class="primary" data-fix-add="${i}">+ Afegir a PeliTrack</button></div></div></article>`).join('');box._fixItems=items};
  const form=document.querySelector('#discoverForm');if(!form)return;
  form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const q=document.querySelector('#discoverSearch').value.trim();if(q.length<2)return;const status=document.querySelector('#discoverStatus');status.textContent='Buscant…';try{const r=await fetch(`${API}?q=${encodeURIComponent(q)}&L=es_ES`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error();render(collect(await r.json(),q),q)}catch{document.querySelector('#discoverResults').innerHTML='';status.textContent='No s’ha pogut fer la cerca.'}},true);
  document.querySelector('#discoverResults')?.addEventListener('click',async e=>{const b=e.target.closest('[data-fix-add]');if(!b)return;const m=document.querySelector('#discoverResults')._fixItems?.[Number(b.dataset.fixAdd)];if(!m)return;try{const r=await fetch('/api/movies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:m.title,year:m.year?Number(m.year):null,genre:m.genre||null,duration_minutes:m.duration,poster_url:m.poster||null,favorite:false,watched:false,watched_at:null,parent_movie_id:null})});if(!r.ok)throw new Error();b.textContent='✓ Afegida';b.disabled=true}catch{b.textContent='Error'}});
})();
