(() => {
  const API='https://imdb.iamidiotareyoutoo.com/justwatch';
  const providers=['Netflix','Disney+','Prime Video','Movistar Plus+'];
  const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const exact=(q,t)=>norm(q)===norm(t);
  const first=(o,keys)=>{for(const k of keys)if(o&&o[k]!=null&&typeof o[k]!=='object')return String(o[k]);return ''};
  const allStrings=(o,out=[])=>{if(o==null)return out;if(Array.isArray(o)){o.forEach(x=>allStrings(x,out));return out}if(typeof o!=='object')return out;for(const [k,v] of Object.entries(o)){if(typeof v==='string')out.push([k,v]);else if(v&&typeof v==='object')allStrings(v,out)}return out};
  const providerNames=o=>{const text=JSON.stringify(o||{}).toLowerCase();const map={Netflix:['netflix','provider_id\\":8'], 'Disney+':['disney+','disney plus','provider_id\\":337'], 'Prime Video':['prime video','amazon video','provider_id\\":9'], 'Movistar Plus+':['movistar','provider_id\\":149','provider_id\\":318']};return providers.filter(p=>map[p].some(x=>text.includes(x)))};
  const providerForUrl=url=>{try{const h=new URL(url).hostname.toLowerCase();if(h==='netflix.com'||h.endsWith('.netflix.com'))return'Netflix';if(h==='disneyplus.com'||h.endsWith('.disneyplus.com'))return'Disney+';if(h==='primevideo.com'||h.endsWith('.primevideo.com')||h==='amazon.com'||h.endsWith('.amazon.com'))return'Prime Video';if(h==='movistarplus.es'||h.endsWith('.movistarplus.es')||h==='movistar.es'||h.endsWith('.movistar.es'))return'Movistar Plus+'}catch{}return null};
  const streamingLinks=o=>{const found={};for(const [k,v] of allStrings(o)){if(!/^https?:\/\//i.test(v)||/\.(jpg|jpeg|png|webp|avif)(\?|$)/i.test(v))continue;const p=providerForUrl(v);if(p&&!found[p])found[p]=v}return found};
  const posterFrom=o=>{const entries=allStrings(o);for(const [k,v] of entries){if(/^https?:\/\//i.test(v)&&/(poster|image|thumbnail|cover)/i.test(k)&&/\.(jpg|jpeg|png|webp|avif)(\?|$)/i.test(v))return v}return''};
  function collect(raw,q){const roots=Array.isArray(raw)?raw:(raw?.items||raw?.results||raw?.data||raw?.titles||raw?.shows||raw?.movies||[raw]);const out=[],seen=new Set();const walk=x=>{if(!x||typeof x!=='object'||out.length>=1)return;if(Array.isArray(x)){for(const v of x){walk(v);if(out.length>=1)break}return}const title=first(x,['title','name','original_title','originalTitle']);if(title&&exact(q,title)){const year=first(x,['year','release_year','releaseYear','original_release_year']),key=(title+'|'+year).toLowerCase();if(!seen.has(key)){seen.add(key);const streaming_urls=streamingLinks(x),fallbackPoster=posterFrom(x),platformUrl=Object.values(streaming_urls)[0]||'';out.push({title,year,poster_url:fallbackPoster,streaming_urls,movie_url:platformUrl,genre:first(x,['genre','genres']),duration:first(x,['runtime','duration','runtime_minutes','duration_minutes']),providers:[...new Set([...providerNames(x),...Object.keys(streaming_urls)])]})}}if(out.length<1)Object.values(x).forEach(v=>v&&typeof v==='object'&&out.length<1&&walk(v))};roots.forEach(walk);for(const m of out){const n=parseInt(String(m.duration??'').replace(/[^0-9]/g,''),10);m.duration=Number.isFinite(n)?n:null}return out.slice(0,1)}
  const render=(items,q)=>{const box=document.querySelector('#discoverResults'),status=document.querySelector('#discoverStatus');if(!items.length){box.innerHTML='';status.textContent=`No s'ha trobat «${q}».`;return}status.textContent='1 resultat';box.innerHTML=items.map((m,i)=>`<article class="discover-card"><div class="discover-poster">${m.poster_url?`<img src="${esc(m.poster_url)}" alt="Pòster de ${esc(m.title)}" loading="lazy">`:'<span>🎬</span>'}</div><div class="discover-info"><h3>${esc(m.title)}</h3><p>${esc(m.year||'Any desconegut')}${m.genre?` · ${esc(m.genre)}`:''}${m.duration?` · ${m.duration} min`:''}</p><div class="discover-providers">${m.providers.map(p=>`<span class="discover-provider">${esc(p)}</span>`).join('')}</div><div class="discover-actions">${m.movie_url?`<a class="secondary" href="${esc(m.movie_url)}" target="_blank" rel="noopener">🔗 Veure</a>`:''}<button class="primary" data-fix-add="${i}">+ Afegir a PeliTrack</button></div></div></article>`).join('');box._fixItems=items};
  const form=document.querySelector('#discoverForm');if(!form)return;
  form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const q=document.querySelector('#discoverSearch').value.trim();if(q.length<2)return;document.querySelector('#discoverStatus').textContent='Buscant…';try{const r=await fetch(`${API}?q=${encodeURIComponent(q)}&L=es_ES`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error();render(collect(await r.json(),q),q)}catch{document.querySelector('#discoverResults').innerHTML='';document.querySelector('#discoverStatus').textContent='No s’ha pogut fer la cerca.'}},true);
  document.querySelector('#discoverResults')?.addEventListener('click',async e=>{const b=e.target.closest('[data-fix-add]');if(!b)return;const m=document.querySelector('#discoverResults')._fixItems?.[Number(b.dataset.fixAdd)];if(!m)return;try{const r=await fetch('/api/movies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:m.title,year:m.year?Number(m.year):null,genre:m.genre||null,duration_minutes:m.duration,poster_url:m.movie_url||m.poster_url||null,movie_url:m.movie_url||null,streaming_urls:m.streaming_urls||{},favorite:false,watched:false,watched_at:null,parent_movie_id:null})});if(!r.ok)throw new Error();b.textContent='✓ Afegida';b.disabled=true}catch{b.textContent='Error'}});
})();
